config/routes.rb
DocTico::Application.routes.draw do
  
  match '/api/api_doc_tico/autenticar_usuario',     to: 'api/api_doc_tico#autenticar_usuario',     via: ['get', 'post']
  match '/api/api_doc_tico/nuevo_usuario',          to: 'api/api_doc_tico#nuevo_usuario',          via: 'get'
  match '/api/api_doc_tico/cerrar_sesion',          to: 'api/api_doc_tico#cerrar_sesion',          via: 'get'  
  match '/api/api_doc_tico/centros_salud',          to: 'api/api_doc_tico#centros_salud',          via: 'get'
  match '/api/api_doc_tico/nombres_centros_salud',  to: 'api/api_doc_tico#nombres_centros_salud',  via: 'get'
  match '/api/api_doc_tico/citas',                  to: 'api/api_doc_tico#citas',                  via: 'get' 
  match '/api/api_doc_tico/nueva_cita',             to: 'api/api_doc_tico#nueva_cita',             via: 'get' 
  match '/api/api_doc_tico/presion_arterial',       to: 'api/api_doc_tico#presion_arterial',       via: 'get' 
  match '/api/api_doc_tico/nueva_presion_arterial', to: 'api/api_doc_tico#nueva_presion_arterial', via: 'get' 

  resources :usuarios

  get "welcome/index"
  resources :centros
  resources :sesiones, only: [:new, :create, :destroy]

  root 'welcome#index'

  match '/signup',  to: 'usuarios#new',         via: 'get'
  match '/signin',  to: 'sesiones#new',         via: 'get'
  match '/signout', to: 'sesiones#destroy',     via: 'delete'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li><%= link_to 'DocTico', root_path %></li>
        </ul>
      <ul class="nav navbar-nav navbar-right">
           <li> <%= link_to "Crea tu propia cuenta en DocTico!", signup_path %></li>
      </ul>
    </div>
</nav>


<div class="panel panel-success">

          <div class="panel-heading">
            <h1 class="panel-title"> <center><h2>DocTico</h2> </center> </h1>
          </div>
				
          <div class="panel-body">
				
            <div align="center" style="height: 450px; overflow: auto;">

                <p>DocTico, la Aplicacion para dispositivos android que te permite encontrar los centros de salud mas cercanos a tu poscision actual!!</p>

                <% if current_user.nil? %>
                  <p><%= link_to 'Iniciar Sesion', signin_path %></p>
                  <p>Eres un nuevo usuario? <%= link_to "Crea tu propia cuenta en DocTico!", signup_path %></p>
                <% end %>

                <% if !current_user.nil? %>
                   <p><%= link_to 'Mi Perfil', usuario_path(current_user) %></p>
                <% end %>
            </div>
         </div>
</div>