config/routes.rb
DocTico::Application.routes.draw do
  
  match '/api/api_doc_tico/autenticar_usuario',     to: 'api/api_doc_tico#autenticar_usuario',     via: ['get', 'post']
  match '/api/api_doc_tico/nuevo_usuario',          to: 'api/api_doc_tico#nuevo_usuario',          via: 'get'
  match '/api/api_doc_tico/cerrar_sesion',          to: 'api/api_doc_tico#cerrar_sesion',          via: 'get'  
  match '/api/api_doc_tico/centros_salud',          to: 'api/api_doc_tico#centros_salud',          via: 'get'
  match '/api/api_doc_tico/nombres_centros_salud',  to: 'api/api_doc_tico#nombres_centros_salud',  via: 'get'
  match '/api/api_doc_tico/citas',                  to: 'api/api_doc_tico#citas',                  via: 'get' 
  match '/api/api_doc_tico/nueva_cita',             to: 'api/api_doc_tico#nueva_cita',             via: 'get' 
  match '/api/api_doc_tico/presion_arterial',       to: 'api/api_doc_tico#presion_arterial',       via: 'get' 
  match '/api/api_doc_tico/nueva_presion_arterial', to: 'api/api_doc_tico#nueva_presion_arterial', via: 'get' 

  resources :usuarios

  get "welcome/index"
  resources :centros
  resources :sesiones, only: [:new, :create, :destroy]

  root 'welcome#index'

  match '/signup',  to: 'usuarios#new',         via: 'get'
  match '/signin',  to: 'sesiones#new',         via: 'get'
  match '/signout', to: 'sesiones#destroy',     via: 'delete'

end

app/controllers/sesiones_controller.rb
class SesionesController < ApplicationController

 def new
  end

  def create
    usuario = Usuario.find_by(email: params[:sesion][:email].downcase)
    if usuario && usuario.authenticate(params[:sesion][:password])
      sign_in usuario
      redirect_to usuario
    else
      render 'new'
    end
  end


  def destroy
    sign_out
    redirect_to root_url
  end
end

app/helpers/sesiones_helper.rb
module SesionesHelper
  
  def sign_in(usuario)
    cookies.permanent[:remember_token] = usuario.remember_token
    self.current_user = usuario
  end

  def signed_in?
    !current_user.nil?
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def current_user=(usuario)
    @current_user = usuario
  end

  def current_user
    @current_user ||= Usuario.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(usuario)
    usuario == current_user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end

end

app/views/sesiones/new.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li><%= link_to 'DocTico', root_path %></li>
        </ul>
      <ul class="nav navbar-nav navbar-right">
           <li> <%= link_to "Crea tu propia cuenta en DocTico!", signup_path %></li>
      </ul>
    </div>
</nav>


<div class="panel panel-success">

          <div class="panel-heading">
            <h3 class="panel-title"><center> Iniciar Sesion en <%= link_to 'DocTico', root_path %> </center> </h3>
          </div>
				
          <div class="panel-body">
				
            <div align="center" style="height: 495px; overflow: auto;">

                <%= form_for(:sesion, url: sesiones_path) do |f| %>

                 <p>
                   <%= f.label :email %>  <br>
                   <%= f.text_field :email %>
                 </p>

                 <p>
                   <%= f.label :password, "Contraseña" %>  <br>
                   <%= f.password_field :password %>
                 </p>

                 <p>
                   <%= f.submit "Iniciar Sesion"%>
                 </p>

                <% end %>

                <p>Eres un nuevo usuario? <%= link_to "Crea tu propia cuenta en DocTico!", signup_path %></p>

            </div>
         </div>
</div>