config/routes.rb
DocTico::Application.routes.draw do
  
  match '/api/api_doc_tico/autenticar_usuario',     to: 'api/api_doc_tico#autenticar_usuario',     via: ['get', 'post']
  match '/api/api_doc_tico/nuevo_usuario',          to: 'api/api_doc_tico#nuevo_usuario',          via: 'get'
  match '/api/api_doc_tico/cerrar_sesion',          to: 'api/api_doc_tico#cerrar_sesion',          via: 'get'  
  match '/api/api_doc_tico/centros_salud',          to: 'api/api_doc_tico#centros_salud',          via: 'get'
  match '/api/api_doc_tico/nombres_centros_salud',  to: 'api/api_doc_tico#nombres_centros_salud',  via: 'get'
  match '/api/api_doc_tico/citas',                  to: 'api/api_doc_tico#citas',                  via: 'get' 
  match '/api/api_doc_tico/nueva_cita',             to: 'api/api_doc_tico#nueva_cita',             via: 'get' 
  match '/api/api_doc_tico/presion_arterial',       to: 'api/api_doc_tico#presion_arterial',       via: 'get' 
  match '/api/api_doc_tico/nueva_presion_arterial', to: 'api/api_doc_tico#nueva_presion_arterial', via: 'get' 

  resources :usuarios

  get "welcome/index"
  resources :centros
  resources :sesiones, only: [:new, :create, :destroy]

  root 'welcome#index'

  match '/signup',  to: 'usuarios#new',         via: 'get'
  match '/signin',  to: 'sesiones#new',         via: 'get'
  match '/signout', to: 'sesiones#destroy',     via: 'delete'

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  has_many :centros, dependent: :destroy
  has_many :presion_arterials, dependent: :destroy
  has_many :citas, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }


  def Usuario.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def Usuario.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = Usuario.hash(Usuario.new_remember_token)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:edit, :update, :show, :index]
  before_action :correct_user,   only: [:edit, :update]

  def index
    if current_user.administrador?
   	 @usuarios = Usuario.all
    else
	redirect_to usuario_path(current_user)
    end
    
  end

  def show
    @usuario = Usuario.find(params[:id])  
    @centros = @usuario.centros
  end

  def new
    @usuario = Usuario.new
  end

  def edit
  end

  def create
    @usuario = Usuario.new(usuario_params)

      if @usuario.save
        redirect_to @usuario
    else
      render 'new'
    end
  end

  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :email, :password, :password_confirmation)
    end

    def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end

    def correct_user
     @usuario = Usuario.find(params[:id])
      redirect_to(root_url) unless current_user?(@usuario)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "errore") %> por lo cual no se puede crear la cuenta:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password, "Contraseña" %><br>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation, "Confirmar Contraseña" %><br>
    <%= f.password_field :password_confirmation %>
  </p>

  <p>
    <%= f.submit 'Crear una Cuenta' %>
  </p>
<% end %>

app/views/usuarios/edit.html.erb
<nav class="navbar navbar-default" role="navigation">

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li><%= link_to @current_user.nombre, usuario_path(current_user) %></li>
        </ul>

      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Cerrar Sesion", signout_path, method: "delete" %>  </li>
      </ul>
    </div>
</nav>


<div class="panel panel-success">

          <div class="panel-heading">
            <h3 class="panel-title"><center>Editar mi Cuenta de <%= link_to 'DocTico', root_path %> </h3>
          </div>
				
          <div class="panel-body">
				
            <div align="center" style="height: 495px; overflow: auto;">

              <%= form_for(@usuario) do |f| %>
                <% if @usuario.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@usuario.errors.count, "errore") %> por lo cual no se puede actualizar los datos la cuenta:</h2>

                    <ul>
                    <% @usuario.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>

                <p>
                  <%= f.label :nombre %><br>
                  <%= f.text_field :nombre %>
                </p>

                <p>
                  <%= f.label :email %><br>
                  <%= f.text_field :email %>
                </p>

                <p>
                  <%= f.label :password, "Contraseña" %><br>
                  <%= f.password_field :password %>
                </p>

                <p>
                  <%= f.label :password_confirmation, "Confirmar Contraseña" %><br>
                  <%= f.password_field :password_confirmation %>
                </p>

                <p>
                  <%= f.submit 'Actualizar mis Datos' %>
                </p>
               <% end %>

            </div>
         </div>
</div>

app/views/usuarios/index.html.erb
<nav class="navbar navbar-default" role="navigation">

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li><%= link_to @current_user.nombre, usuario_path(current_user) %></li>
        </ul>

      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Cerrar Sesion", signout_path, method: "delete" %>  </li>
      </ul>
    </div>
</nav>


<div class="panel panel-success">

          <div class="panel-heading">
            <h3 class="panel-title"> <center> Lista de Usuarios de <%= link_to 'DocTico', root_path %>: (<%= @usuarios.count %>) </center> </h3>
          </div>
				
          <div class="panel-body">
				
            <div align="center" style="height: 495px; overflow: auto;">
					
              <table class="table table-striped">
                <tr>
                  <th>Nombre</th>
                  <th>Email</th>
                  <th></th>
                  <th></th>
                  <th></th>
                </tr>

                    <% @usuarios.each do |usuario| %>
                      <tr>
                        <td><%= usuario.nombre %></td>
                        <td><%= usuario.email %></td>

                          <td><%= link_to usuario do %>
                              <span class="glyphicon glyphicon-new-window"></span>
                          <% end %></td>

                        <% if !current_user.nil? %>
                        <td>  <% if current_user.administrador? && !current_user?(usuario) %>
                            <td><%= link_to usuario, :method => :delete, :confirm => "Esta seguro de eliminar esta cuenta?" do %>
                              <span class="glyphicon glyphicon-trash"></span>
                            <% end %> </td> 
                        <% end %>
                    <% end %>

                      </tr>
                    <% end %>

              </table>
            </div>
         </div>
</div>

app/views/usuarios/new.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li><%= link_to 'DocTico', root_path %></li>
        </ul>
    </div>
</nav>

<div class="panel panel-success">

          <div class="panel-heading">
            <h3 class="panel-title"><center> Crear una cuenta en <%= link_to 'DocTico', root_path %> </center> </h3>
          </div>
				
          <div class="panel-body">
				
            <div align="center" style="height: 495px; overflow: auto;">

              <%= render 'form' %>

              <p>
              <%= link_to 'Ir a DocTico.com', root_path %>
              </p>
            </div>
         </div>
</div>

app/views/usuarios/show.html.erb
<nav class="navbar navbar-default" role="navigation">

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li><%= link_to @current_user.nombre, usuario_path(current_user) %></li>

            <li><%= link_to @current_user.email, usuario_path(current_user) %></li>
        </ul>

      <ul class="nav navbar-nav navbar-right">

              <% if @current_user == @usuario %>

                  <li><%= link_to 'Editar esta Cuenta', edit_usuario_path(@usuario) %> </li>
                  <li><%= link_to "Eliminar esta Cuenta", @usuario, method: :delete,  
                                     data: { confirm: "Esta seguro de eliminar la cuenta?" } %></li>
             <% end %>

          <li><%= link_to "Cerrar Sesion", signout_path, method: "delete" %>  </li>
      </ul>
    </div>
</nav>

  <div class="panel panel-success">

    <div class="panel-heading">
      <h3 class="panel-title">
        <% if current_user == @usuario%>
          <%= link_to 'Agregar un nuevo Centro de Salud', new_centro_path %> |    -    |
          <%= link_to 'Ver todos los Centros de Salud en DocTico', centros_path %> |    -    |

          <% if @current_user.administrador? %>
            <%= link_to 'Ver todos los usuarios', usuarios_path %>
          <% end %>
        <% end %>
      </h3>
    </div>
	
   <% if @current_user != @usuario %>
            <p>Nombre de Usuario: <%=@usuario.nombre%></p>
            <p>Email: <%=@usuario.email%></p>
   <% end %>

    <div class="panel-body">
      <% if @usuario.centros.any? %>
        <div class="panel panel-success">

          <div class="panel-heading">
            <h3 class="panel-title">Mis Centros de Salud (<%= @usuario.centros.count %>)</h3>
          </div>
				
          <div class="panel-body">
				
            <div align="center" style="height: 405px; overflow: auto;">
					
              <table class="table table-striped">
                <tr>		
                  <th>Nombre</th>
                  <th>Latitud</th>
                  <th>Longitud</th>
                  <th>Tipo</th>
                  <th>Horario</th>
                  <th>Descripcion</th>
                  <th></th>
                  <th></th>
                </tr>

			         <%= render @centros %>

              </table>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>