config/routes.rb
DocTico::Application.routes.draw do
  
  match '/api/api_doc_tico/autenticar_usuario',     to: 'api/api_doc_tico#autenticar_usuario',     via: ['get', 'post']
  match '/api/api_doc_tico/nuevo_usuario',          to: 'api/api_doc_tico#nuevo_usuario',          via: 'get'
  match '/api/api_doc_tico/cerrar_sesion',          to: 'api/api_doc_tico#cerrar_sesion',          via: 'get'  
  match '/api/api_doc_tico/centros_salud',          to: 'api/api_doc_tico#centros_salud',          via: 'get'
  match '/api/api_doc_tico/nombres_centros_salud',  to: 'api/api_doc_tico#nombres_centros_salud',  via: 'get'
  match '/api/api_doc_tico/citas',                  to: 'api/api_doc_tico#citas',                  via: 'get' 
  match '/api/api_doc_tico/nueva_cita',             to: 'api/api_doc_tico#nueva_cita',             via: 'get' 
  match '/api/api_doc_tico/presion_arterial',       to: 'api/api_doc_tico#presion_arterial',       via: 'get' 
  match '/api/api_doc_tico/nueva_presion_arterial', to: 'api/api_doc_tico#nueva_presion_arterial', via: 'get' 

  resources :usuarios

  get "welcome/index"
  resources :centros
  resources :sesiones, only: [:new, :create, :destroy]

  root 'welcome#index'

  match '/signup',  to: 'usuarios#new',         via: 'get'
  match '/signin',  to: 'sesiones#new',         via: 'get'
  match '/signout', to: 'sesiones#destroy',     via: 'delete'

end

app/models/centro.rb
class Centro < ActiveRecord::Base
  belongs_to :usuario
  validates :usuario_id, presence: true
  validates :nombre, presence: true
  validates :latitud, presence: true
  validates :longitud, presence: true
  validates :tipo, presence: true
  validates :horario, presence: true
  validates :descripcion, presence: true
end

app/controllers/api/centros_controller.rb
class Api::CentrosController < ApplicationController
  def index
    @centros = Centro.all
  end

  def autenticar_usuario
   @mensaje = Mensaje.new

    @usuario = Usuario.find_by Email: params[:email]
   
   #  usuario = Usuario.find_by Email: params[:email]
   # if usuario && usuario.authenticate(params[:password])
   #   @mensaje.respuesta = "Si"
   # else
   #   @mensaje.respuesta = "No"
   #end
  end
end


# Esta clase es para devolver el token
# Estoy usando la geme jsonBuilder
class Mensaje
  attr_accessor :respuesta
  @respuesta
end

app/controllers/centros_controller.rb
class CentrosController < ApplicationController
  before_action :signed_in_user

def new
  @centro = Centro.new
  @tipos_centro = TipoCentro.all
end

def create
  @centro = current_user.centros.build(post_params)
  
  if  @centro.save
    redirect_to @centro
  else
    render 'new'
  end
end

def show
  @centro = Centro.find(params[:id])
end

def index
   @centros = Centro.all
end

def edit
  @centro = Centro.find(params[:id])
  @tipos_centro = TipoCentro.all
end

def update
  @centro = Centro.find(params[:id])
 
   if @centro.update(params.require(:centro).permit(:nombre, :longitud, :latitud, :tipo, :horario, :descripcion))
    redirect_to @centro
  else
    render 'edit'
  end
end

def destroy
  @centro = Centro.find(params[:id])
  @centro.destroy
 
  redirect_to usuario_path(current_user)
end

private
  def post_params
    params.require(:centros).permit(:nombre, :longitud, :latitud, :tipo, :horario, :descripcion)
  end
end

app/helpers/api/centros_helper.rb
module Api::CentrosHelper
end

app/helpers/centros_helper.rb
module CentrosHelper
end

app/views/centros/_centro.html.erb
    <tr>
      <td><%= centro.nombre %></td>
      <td><%= centro.longitud %></td>
      <td><%= centro.latitud %></td>
      <td><%= centro.tipo %></td>
      <td><%= centro.horario %></td>
      <td><%= centro.descripcion %></td>

    <% if current_user == @usuario%>

      <td><%= link_to  edit_centro_path(centro) do %>
          <span class="glyphicon glyphicon-edit"></span>
      <% end %></td>

      <td><%= link_to centro_path(centro), :method => :delete, :confirm => "Esta seguro de eliminar??" do %>
        <span class="glyphicon glyphicon-trash"></span>
      <% end %> </td> 
    <% end %>
   </tr>

app/views/centros/edit.html.erb
<nav class="navbar navbar-default" role="navigation">

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li><%= link_to @current_user.nombre, usuario_path(current_user) %></li>
        </ul>

      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Cerrar Sesion", signout_path, method: "delete" %>  </li>
      </ul>
    </div>
</nav>

<div class="panel panel-success">

          <div class="panel-heading">
            <h3 class="panel-title"><center>Editando el centro de salud <%= @centro.nombre %> </h3>
          </div>
				
          <div class="panel-body">
				
            <div align="center" style="height: 495px; overflow: auto;">

              <%= form_for :centro, url: centro_path(@centro), method: :patch do |f| %>
                <% if @centro.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@centro.errors.count, "error") %> Hay errores:</h2>
                  <ul>
                  <% @centro.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                  </ul>
                </div>
                <% end %>

                <p>
                  <%= f.label :nombre %><br>
                  <%= f.text_field :nombre %>
                </p>
               
                <p>
                  <%= f.label :latitud %><br>
                  <%= f.text_field :longitud %>
                </p>

                <p>
                  <%= f.label :longitud %><br>
                  <%= f.text_field :latitud %>
                </p>

                <p>
                  <%= f.label :tipo_de_centro %><br>
                  <%= f.text_field :tipo %>
                </p>

                <p>
                  <%= f.label :horario %><br>
                  <%= f.text_area :horario %>
                </p>

                <p>
                  <%= f.label :descripcion %><br>
                  <%= f.text_area :descripcion %>
                </p>
               
                <p>
                  <%= f.submit 'Actualizar los Datos del Centro' %>
                </p>
              <% end %>
            </div>
         </div>
</div>

app/views/centros/index.html.erb
<nav class="navbar navbar-default" role="navigation">

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li><%= link_to @current_user.nombre, usuario_path(current_user) %></li>
        </ul>

      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Cerrar Sesion", signout_path, method: "delete" %>  </li>
      </ul>
    </div>
</nav>




<div class="panel panel-success">

          <div class="panel-heading">
            <h3 class="panel-title"><center> Lista de los Centros de Salud de <%= link_to 'DocTico', root_path %>: (<%= @centros.count %>) </center> </h3>
          </div>
				
          <div class="panel-body">
				
            <div align="center" style="height: 495px; overflow: auto;">
					
              <table class="table table-striped">
                <tr>		
                  <th>Nombre</th>
                  <th>Longitud</th>
                  <th>Latitud</th>
                  <th>Tipo</th>
                  <th>Horario</th>
                  <th>Descripcion</th>
                </tr>

			         <%= render @centros %>

              </table>
            </div>
         </div>
</div>

app/views/centros/new.html.erb
<nav class="navbar navbar-default" role="navigation">

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li><%= link_to @current_user.nombre, usuario_path(current_user) %></li>
        </ul>

      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Cerrar Sesion", signout_path, method: "delete" %>  </li>
      </ul>
    </div>
</nav>




<div class="panel panel-success">

          <div class="panel-heading">
            <h3 class="panel-title"><center> Nuevo Centro de Salud en <%= link_to 'DocTico', root_path %> </center> </h3>
          </div>
				
          <div class="panel-body">
				
            <div align="center" style="height: 495px; overflow: auto;">


              <%= form_for :centros, url: centros_path do |f| %>
                
              <% if @centro.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@centro.errors.count, "error") %> no se puede guardar:</h2>
                  <ul>
                  <% @centro.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                  </ul>
                </div>
                <% end %>

                <p>
                  <%= f.label :nombre %><br>
                  <%= f.text_field :nombre %>
                </p>
               
                <p>
                  <%= f.label :latitud %><br>
                  <%= f.text_field :longitud %>
                </p>

                <p>
                  <%= f.label :longitud %><br>
                  <%= f.text_field :latitud %>
                </p>

                <p>
                  <%= f.label :tipo_de_centro %><br>
                  <%= f.text_field :tipo %>
                </p>

                <p>
                  <%= f.label :horario %><br>
                  <%= f.text_area :horario %>
                </p>

                <p>
                  <%= f.label :descripcion %><br>
                  <%= f.text_area :descripcion %>
                </p>
               
                <p>
                  <%= f.submit "Crear nuevo Centro de Salud"%>
                </p>
              <% end %>

            </div>
         </div>
</div>

app/views/centros/show.html.erb
<nav class="navbar navbar-default" role="navigation">

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li><%= link_to @current_user.nombre, usuario_path(current_user) %></li>
        </ul>

      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Cerrar Sesion", signout_path, method: "delete" %>  </li>
      </ul>
    </div>
</nav>



<div class="panel panel-success">

          <div class="panel-heading">
            <h3 class="panel-title"><center>Centro de salud: <%= @centro.nombre %> </h3>
          </div>
				
          <div class="panel-body">
				
            <div align="center" style="height: 495px; overflow: auto;">

                <p>
                  <strong>Nombre:</strong>
                  <%= @centro.nombre %>
                </p>
                 
                <p>
                  <strong>Longitud:</strong>
                  <%= @centro.longitud %>
                </p>

                <p>
                  <strong>Latitud:</strong>
                  <%= @centro.latitud %>
                </p>

                <p>
                  <strong>Tipo:</strong>
                  <%= @centro.tipo %>
                </p>

                <p>
                  <strong>Horario:</strong>
                  <%= @centro.horario %>
                </p>

                <p>
                  <strong>Descripcion:</strong>
                  <%= @centro.descripcion %>
                </p>

                <%= link_to 'Editar Datos', edit_centro_path(@centro) %>
            </div>
         </div>
</div>